package installer

import (
	"fmt"
	"testing"

	"github.com/golang/mock/gomock"
	"github.com/stretchr/testify/assert"

	mockExtendedK8sClient "github.com/netapp/trident/mocks/mock_operator/mock_controllers/mock_orchestrator/mock_installer"
)

const (
	Namespace = "trident"
)

var (
	encryptSecretName = getEncryptionSecretName()
	k8sClientError    = fmt.Errorf("k8s error")
)

// newMockKubeClient returns a mock k8s client
// Parameters:
//   t *testing.T - test object
// Returns:
//   *mockExtendedK8sClient.MockExtendedK8sClient - mock k8s client
// Example:
//   mockK8sClient := newMockKubeClient(t)
//
// -- Doc autogenerated on 2022-05-12 18:52:24.083540 --
func newMockKubeClient(t *testing.T) *mockExtendedK8sClient.MockExtendedK8sClient {
	mockCtrl := gomock.NewController(t)
	mockK8sClient := mockExtendedK8sClient.NewMockExtendedK8sClient(mockCtrl)
	return mockK8sClient
}

// newTestInstaller creates a new Installer for testing
// It returns a pointer to the Installer and a pointer to the mock client
// Parameters:
//   client - a pointer to a mock client
// Returns:
//   a pointer to the Installer
// Example:
//   installer, client := newTestInstaller(client)
//
// -- Doc autogenerated on 2022-05-12 18:52:24.083540 --
func newTestInstaller(client *mockExtendedK8sClient.MockExtendedK8sClient) *Installer {

	return &Installer{
		client:           client,
		tridentCRDClient: nil,
		namespace:        Namespace,
	}
}

// createTestControllingCRDetails creates a map of the controlling CR details
// It returns a map of the controlling CR details
// Returns:
//   map[string]string: map of the controlling CR details
// Example:
//   crDetails := createTestControllingCRDetails()
//
// -- Doc autogenerated on 2022-05-12 18:52:24.083540 --
func createTestControllingCRDetails() map[string]string {

	controllingCRDetails := make(map[string]string)
	controllingCRDetails[CRAPIVersionKey] = "v01.01.01"
	controllingCRDetails[CRController] = "trident-orchestrator"
	controllingCRDetails[CRKind] = "deployment"
	controllingCRDetails[CRName] = "trident-csi"
	controllingCRDetails[CRUID] = CRUID

	return controllingCRDetails
}

// createTestLabels creates a map of labels for testing
// It returns a map of labels
// Returns:
//   map[string]string: map of labels
// Example:
//   labels := createTestLabels()
//
// -- Doc autogenerated on 2022-05-12 18:52:24.083540 --
func createTestLabels() map[string]string {

	labels := make(map[string]string)
	labels[appLabelKey] = appLabelValue
	labels[K8sVersionLabelKey] = "v1.21.8"
	labels[TridentVersionLabelKey] = "v22.04.0"

	return labels
}

// TestInstaller_createOrConsumeTridentEncryptionSecret tests the createOrConsumeTridentEncryptionSecret function
// It checks for the following conditions:
// 1. K8s error at CheckSecretExists
// 2. Secret already exists and no K8s error
// 3. Create secret with no failure at PutSecret
// 4. Create secret with a failure at PutSecret
//
// -- Doc autogenerated on 2022-05-12 18:52:24.083540 --
func TestInstaller_createOrConsumeTridentEncryptionSecret(t *testing.T) {

	mockK8sClient := newMockKubeClient(t)
	installer := newTestInstaller(mockK8sClient)
	controllingCRDetails := createTestControllingCRDetails()
	labels := createTestLabels()

	// K8s error at CheckSecretExists
	mockK8sClient.EXPECT().CheckSecretExists(encryptSecretName).Return(false, k8sClientError)
	expectedErr := installer.createOrConsumeTridentEncryptionSecret(controllingCRDetails, labels, false)
	assert.NotNil(t, expectedErr, "expected non-nil error")

	// Secret already exists and no K8s error
	mockK8sClient.EXPECT().CheckSecretExists(encryptSecretName).Return(true, nil)
	expectedErr = installer.createOrConsumeTridentEncryptionSecret(controllingCRDetails, labels, false)
	assert.Nil(t, expectedErr, "expected nil error")

	// Create secret with no failure at PutSecret
	mockK8sClient.EXPECT().CheckSecretExists(encryptSecretName).Return(false, nil)
	mockK8sClient.EXPECT().PutSecret(true, gomock.Any(), encryptSecretName).Return(nil)
	expectedErr = installer.createOrConsumeTridentEncryptionSecret(controllingCRDetails, labels, false)
	assert.Nil(t, expectedErr, "expected nil error")

	// Create secret with a failure at PutSecret
	mockK8sClient.EXPECT().CheckSecretExists(encryptSecretName).Return(false, nil)
	mockK8sClient.EXPECT().PutSecret(true, gomock.Any(), encryptSecretName).Return(k8sClientError)
	expectedErr = installer.createOrConsumeTridentEncryptionSecret(controllingCRDetails, labels, false)
	assert.NotNil(t, expectedErr, "expected no nil error")
}
