// Copyright 2020 NetApp, Inc. All Rights Reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/netapp/trident/operator/controllers/provisioner/client/clientset/versioned"
	tridentv1 "github.com/netapp/trident/operator/controllers/provisioner/client/clientset/versioned/typed/netapp/v1"
	faketridentv1 "github.com/netapp/trident/operator/controllers/provisioner/client/clientset/versioned/typed/netapp/v1/fake"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
// Discovery retrieves the DiscoveryClient
// It returns a fake implementation of the discovery client
// Returns:
//   *discovery.DiscoveryClient
// Example:
//   clientset := fake.NewSimpleClientset()
//   discoveryClient := clientset.Discovery()
//
// -- Doc autogenerated on 2022-05-12 19:06:58.435680 --
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

// Tracker is a fake implementation of the Tracker interface.
// It returns fake objects.
// Returns:
//   * fake.Clientset
//   * fake.Tracker
//   * fake.Tracker
// Example:
//   cs := fake.NewSimpleClientset()
//   cs.Tracker()
//
// -- Doc autogenerated on 2022-05-12 19:06:58.435680 --
func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var _ clientset.Interface = &Clientset{}

// TridentV1 retrieves the TridentV1Client
func (c *Clientset) TridentV1() tridentv1.TridentV1Interface {
	return &faketridentv1.FakeTridentV1{Fake: &c.Fake}
}
