// Copyright 2021 NetApp, Inc. All Rights Reserved.

package core

import (
	"io/ioutil"
	"os"
	"testing"

	log "github.com/sirupsen/logrus"
)

// TestMain is the entry point for all unit tests
// It checks for the environment variable TRACE and if set,
// enables debug logging.
//
// -- Doc autogenerated on 2022-05-12 17:31:05.128674 --
func TestMain(m *testing.M) {
	// Disable any standard log output
	log.SetOutput(ioutil.Discard)
	os.Exit(m.Run())
}
