// Copyright 2021 NetApp, Inc. All Rights Reserved.

package core

import (
	"io/ioutil"
	"os"
	"testing"

	log "github.com/sirupsen/logrus"
)

// TestMain is the main entry point for tests
// It checks for a test config file and sets up the test environment
//
// -- Doc autogenerated on 2022-05-12 20:34:20.021163 --
func TestMain(m *testing.M) {
	// Disable any standard log output
	log.SetOutput(ioutil.Discard)
	os.Exit(m.Run())
}
