// Copyright 2020 NetApp, Inc. All Rights Reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/netapp/trident/operator/controllers/provisioner/client/clientset/versioned/typed/netapp/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTridentV1 struct {
	*testing.Fake
}

// TridentProvisioners implements TridentProvisionerInterface
// It returns a fake TridentProvisionerInterface
// Parameters:
//   c - a TridentClient
//   namespace - the namespace
// Returns:
//   a fake TridentProvisionerInterface
// Example:
//   c := fake.NewSimpleClientset()
//   fake.TridentProvisioners(c, "default")
//
// -- Doc autogenerated on 2022-05-12 21:18:39.129394 --
func (c *FakeTridentV1) TridentProvisioners(namespace string) v1.TridentProvisionerInterface {
	return &FakeTridentProvisioners{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTridentV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
