// Copyright 2020 NetApp, Inc. All Rights Reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/netapp/trident/operator/controllers/provisioner/client/clientset/versioned/typed/netapp/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTridentV1 struct {
	*testing.Fake
}

// TridentProvisioners returns a TridentProvisionerInterface.
// Parameters:
//   namespace - namespace of the TridentProvisionerInterface.
// Returns:
//   TridentProvisionerInterface
// Example:
//   kubeClient := fake.NewSimpleClientset()
//   tridentProvisioners := kubeClient.TridentV1().TridentProvisioners("default")
//
// -- Doc autogenerated on 2022-05-12 19:08:18.384280 --
func (c *FakeTridentV1) TridentProvisioners(namespace string) v1.TridentProvisionerInterface {
	return &FakeTridentProvisioners{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTridentV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
